// =============================================================
// ToyModelSOEMC.mod
// Small Open Economy: Multi-Commodity Strategic Reserves + Installed Capacity
//
// Extension of ToyModelSOE.mod:
//   - N dirty energy commodities (default: oil + coal)
//     *** Change the COMM list below to add/remove commodities ***
//   - Each commodity c has its own:
//       E_D_c_import : imports from world market (subject to supply & price shocks)
//       ES_c         : useful ENERGY SERVICES = E_D_c * (Q_c(-1)/Q_c_bar)^(1-alpha_Q)
//       Q_c          : installed conversion capacity (refineries / power plants)
//       R_c          : strategic reserve stock
//       ToT_c        : terms-of-trade cost = eps_c * E_D_c_import
//   - Capacity accumulates via investment IQ_c = phi_IQ * Y / N_COMM (rule)
//   - Monte Carlo analysis in ToyModelSOEMC_montecarlo.m over phi_R x phi_IQ grid
//
// KEY INSIGHT: reserves and capacity are STRATEGIC COMPLEMENTS.
//   Without sufficient Q_c, releasing R_c produces fewer energy services.
//   Optimal policy requires investing in both.
//
// Steady state: identical to ToyModelSOE when phi_IQ -> 0 and N*ED_c_bar = ED_bar
// =============================================================

// ---------------------------------------------------------------
// MACROPROCESSOR CONFIGURATION
// Change COMM to add/remove energy commodities.
// Example 3-commodity model: @#define COMM = ["oil", "coal", "gas"]
// ---------------------------------------------------------------
@#define COMM   = ["oil", "coal"]
@#define N_COMM = length(COMM)
if exist('SIM_MODE', 'var')
    if isequal(SIM_MODE, 'pf')
        @# define SIMMode = "pf"
    else
        @# define SIMMode = "ep"
    end
else
    @# define SIMMode = "pf"
end
// ---------------------------------------------------------------
// Variable declarations (generated by macroprocessor)
// ---------------------------------------------------------------
// Per-commodity endogenous: eps_c (AR(1) price shock state) and R_c_draw (policy rule)
// are now endogenous — driven by iid innovations nu_c and e_c_shock in varexo.
var Y C I K r w p_E E_D_service E NX
@#for c in COMM
    eps_@{c}  R_@{c}_draw  E_D_@{c}_import  E_D_@{c}  ES_@{c}  Q_@{c}  IQ_@{c}  R_@{c}  ToT_@{c}
@#endfor
;

// Two iid innovations per commodity:
//   nu_c     : Gaussian innovation to the AR(1) price shock state eps_c
//   e_c_shock: iid supply disruption (negative = supply shortfall)
varexo
@#for c in COMM
    nu_@{c}  e_@{c}_shock
@#endfor
;

parameters A alpha_K alpha_L alpha_E rho eta beta delta Lbar EC_bar
           delta_R gamma_R p_D_bar alpha_Q delta_Q phi_IQ phi_R rho_p
           kappa_1 kappa_2
@#for c in COMM
    ED_@{c}_bar  Q_@{c}_bar  R_@{c}_bar
@#endfor
;

// ---------------------------------------------------------------
// Calibration — Vietnam SOE (2024 baseline)
//
// Sources: World Bank Vietnam data 2023, IEA Energy Statistics 2023,
//          MOIT Power Development Plan VIII (2023),
//          National Energy Master Plan to 2050 (NEMP 2050, Decision 893/QD-TTg 2023)
//
// KEY MACRO TARGETS:
//   GDP growth (2024-2030): 10% p.a. (13th Party Congress Resolution)
//   Investment/GDP:  ~33%  (capital-intensive development stage)
//   Energy intensity: high relative to income (manufacturing-heavy)
//
// ENERGY PROFILE (2023 primary energy mix):
//   Coal:        ~46% of primary energy (dominant in power generation)
//   Oil/petroleum: ~31% (transport + industry)
//   Gas + renewables: ~12% + 11%  (absorbed into EC_bar)
//   → Dirty energy split: coal 60%, oil 40%  (of ED_total = 0.75)
//
// STRATEGIC PETROLEUM RESERVE:
//   Current: ~30–45 days  |  IEA target: 90 days
//   Model: R_oil_bar = 2.0 × ED_oil_bar (≈ 60-day buffer per quarterly period)
//          R_coal_bar = 1.5 × ED_coal_bar (≈ 45-day stockyard reserve)
// ---------------------------------------------------------------

// --- Macro parameters ---
A       = 1;
alpha_K = 0.38;    // Capital share: ~38% (Vietnam: investment-intensive development stage)
alpha_L = 0.47;    // Labor share:   ~47% (labor-intensive manufacturing + agriculture)
alpha_E = 0.15;    // Energy share:  ~15% (high energy intensity; sums with K+L to 1.0)
eta     = 0.5;     // CES substitution elasticity: lower than advanced economies
rho     = (eta - 1)/eta;
beta    = 0.95;    // Discount factor: real rate ~5.3% p.a. (Vietnam policy rate environment)
delta   = 0.065;   // Capital depreciation: 6.5% p.a. (Vietnam capital stock)
Lbar    = 0.10;      // Normalized labor supply
EC_bar  = 0.25;    // Clean energy baseline (hydro ~25% of primary energy; growing via EMP)

// --- SOE / reserve parameters ---
delta_R = 0.02;    // Reserve physical loss rate (2% p.a. — evaporation, degradation, leakage)
gamma_R = 0.25;    // Reserve refill speed after drawdown: 25% of gap filled per year
                   //   → return from zero to target in ~4 years (realistic for oil terminals)
                   //   SS: refill = delta_R*R_bar (replaces annual losses); no gap-filling needed
                   //   Post-crisis: rapid replenishment. Keeps E[R_c] ≈ R_c_bar across shocks.
p_D_bar = 1.0;     // Normalized baseline world energy price (eps_c measures % deviations)

// --- Capacity parameters ---
alpha_Q = 0.40;    // Raw energy share in energy service production
delta_Q = 0.05;    // Capacity depreciation (5% p.a.)
phi_IQ  = 0.04;    // Capacity investment: 4% of Y per period (shared equally)

// --- Reserve drawdown policy (phi_R varied in MC; endogenous rule) ---
phi_R   = 0.5;
rho_p   = 0.60;    // AR(1) persistence of price shock state

// --- Quadratic storage cost (annual model calibration) ---
//   kappa_1 = delta_R * p_D_bar = 0.02  (linear: 2% physical loss per year — evaporation)
//   kappa_2 = 0.12                       (quadratic: infrastructure + land + insurance cost)
//             Calibrated so MC at 90-day oil coverage = 2x the linear cost:
//               MC(R_oil_90d) = 0.02 + 2*0.12*0.074 ≈ 0.038  → rapidly rising > 90 days
//             Reflects Vietnam's constrained above-ground storage capacity.
//
//   OPTIMAL R_bar* is NOT set here — it emerges from ToyModelSOEMC_optimal_stock.m,
//   which runs a Monte Carlo benefit-cost search and writes R_oil_bar*, R_coal_bar*
//   back to M_.params. Values below are IEA 90-day starting points only.
kappa_1 = delta_R * p_D_bar;   // = 0.02
kappa_2 = 0.12;                // quadratic storage cost (annual model)

// --- Per-commodity calibration (Vietnam energy profile 2024) ---
// Oil/petroleum: 40% of dirty energy  →  ED_oil_bar = 0.40 * 0.75 = 0.30
// Coal:          60% of dirty energy  →  ED_coal_bar = 0.60 * 0.75 = 0.45
// (Total dirty energy ED_total = 0.75; EC_bar = 0.25 → E_ss = 1.0 unchanged)
ED_oil_bar  = 0.30;     // Oil/petroleum imports (normalized; 40% of dirty energy)
ED_coal_bar = 0.45;     // Coal imports (normalized; 60% of dirty energy — Vietnam coal-dominant)

// Strategic reserve STARTING VALUES — IEA 90-day standard (ANNUAL model):
//   Model period = 1 year. Coverage = R_c_bar / ED_c_bar * 365 days.
//   90-day standard: R_c_bar = (90/365) * ED_c_bar
//     R_oil_bar  = (90/365) * 0.30 ≈ 0.074  (NOT 2*0.30 which would be 2 full years!)
//     R_coal_bar = (90/365) * 0.45 ≈ 0.111
//   These are overwritten by ToyModelSOEMC_optimal_stock.m with the model-optimal values.
R_oil_bar  = (90.0 / 365.0) * ED_oil_bar;    // ≈ 0.074  (IEA 90-day starting point)
R_coal_bar = (90.0 / 365.0) * ED_coal_bar;   // ≈ 0.111  (IEA 90-day starting point)

@#for c in COMM
    Q_@{c}_bar  = 18.0;    // placeholder: overwritten by steadystate solver
@#endfor

// ---------------------------------------------------------------
// Model
// ---------------------------------------------------------------
model;

// -------  Per-commodity block (generated for each c in COMM)  -------
@#for c in COMM

    // AR(1) price shock state: eps_c = rho_p*eps_c(-1) + nu_c
    //   In SS: eps_c = 0.  nu_c is iid N(0, sigma_nu^2) from the shocks block.
    //   eps_c > 0 means import prices are above the baseline p_D_bar.
    eps_@{c} = rho_p * eps_@{c}(-1) + nu_@{c};

    // Reserve drawdown rule — ANNUAL SUPPLY SHORTAGE LOGIC:
    //
    //   Annual shortage = max(0, -e_c_shock)  [imports below baseline in a crisis year]
    //   Desired drawdown = phi_R * shortage   [policy: release phi_R fraction of the gap]
    //   Actual drawdown  = min(desired, R_c(-1))  [can't release more than available stock]
    //
    //   If shortage <= R_c(-1)/phi_R : reserves fully offset phi_R*shortage, no production hit
    //   If shortage >  R_c(-1)/phi_R : reserves exhausted mid-crisis, residual shortage hits Y
    //
    //   NOTE: Only supply shortages trigger drawdown (security purpose).
    //   Price-based drawdown is excluded: price spikes and supply crises are independent events
    //   and should not compete for the same stock. Governments draw on SPRs for physical
    //   security (Malacca Strait blockage), not as a price-arbitrage instrument.
    R_@{c}_draw = min(phi_R * max(0, -e_@{c}_shock), R_@{c}(-1));

    // Import supply from world market; e_c_shock < 0 = supply disruption
    E_D_@{c}_import = ED_@{c}_bar + e_@{c}_shock;

    // Total commodity use = imports + reserve release
    E_D_@{c} = E_D_@{c}_import + R_@{c}_draw;

    // Useful energy services: capacity-constrained
    //   In SS: Q_c(-1)=Q_c_bar -> ES_c = E_D_c (full efficiency)
    //   Below-SS capacity: ES_c < E_D_c (reserve releases less effective)
    ES_@{c} = E_D_@{c} * (Q_@{c}(-1) / Q_@{c}_bar)^(1 - alpha_Q);

    // Capacity investment rule: share phi_IQ of output, split equally
    IQ_@{c} = phi_IQ * Y / @{N_COMM};

    // Capacity accumulation (like capital, but for energy conversion infrastructure)
    Q_@{c} = (1 - delta_Q)*Q_@{c}(-1) + IQ_@{c};

    // Reserve dynamics — two-component refill:
    //   delta_R * R_c_bar  : replaces annual physical losses (maintenance refill)
    //   gamma_R * max(0, R_c_bar - R_c(-1)) : gap-filling after drawdown
    //     In SS: gap = 0 → only maintenance refill active → R_c_bar = (1-delta_R)*R_c_bar + delta_R*R_c_bar ✓
    //     Post-crisis (gap > 0): rapid replenishment; return to target in 1/gamma_R ≈ 4 years
    //   No max(0,...) needed: drawdown is capped at R_c(-1) above, so R_c >= 0 always.
    R_@{c} = (1 - delta_R)*R_@{c}(-1) - R_@{c}_draw
           + delta_R * R_@{c}_bar
           + gamma_R * max(0, R_@{c}_bar - R_@{c}(-1));

    // Terms-of-trade cost: extra import bill from world price shock
    ToT_@{c} = eps_@{c} * E_D_@{c}_import;

@#endfor

// -------  Aggregation  -------

    // Total useful dirty energy services (linear aggregation across commodities)
    E_D_service =
    @#for j in 1:N_COMM
        @#if j > 1
        +
        @#endif
        ES_@{COMM[j]}
    @#endfor
    ;

    // Total energy entering production
    E = E_D_service + EC_bar;

// -------  Production (CES, unchanged from original ToyModel)  -------

    Y = A*(alpha_K*K(-1)^rho + alpha_L*Lbar^rho + alpha_E*E^rho)^(1/rho);

    r   = A*alpha_K*(K(-1)^(rho-1))*(alpha_K*K(-1)^rho + alpha_L*Lbar^rho + alpha_E*E^rho)^(1/rho - 1);
    w   = A*alpha_L*(Lbar^(rho-1))  *(alpha_K*K(-1)^rho + alpha_L*Lbar^rho + alpha_E*E^rho)^(1/rho - 1);
    p_E = A*alpha_E*(E^(rho-1))     *(alpha_K*K(-1)^rho + alpha_L*Lbar^rho + alpha_E*E^rho)^(1/rho - 1);

// -------  Resource constraint (modified: capacity investment + ToT + storage cost)  -------
//   Storage cost enters as a flow cost: each period, the economy uses resources
//   to maintain the reserve stock (depreciation replacement + infrastructure).
//   Using R_c(-1) because storage costs are incurred on the beginning-of-period stock.

    Y = C + I
    @#for c in COMM
        + IQ_@{c} + ToT_@{c}
        + kappa_1 * R_@{c}(-1) + kappa_2 * R_@{c}(-1)^2
    @#endfor
    ;

// -------  Capital accumulation and Euler equation (unchanged)  -------

    K = (1 - delta)*K(-1) + I;
    1/C = beta*(1/C(+1))*(r(+1) + 1 - delta);

// -------  Trade balance  -------

    NX = 0
    @#for c in COMM
        - ToT_@{c}
    @#endfor
    ;

end;

// ---------------------------------------------------------------
// Steady state — only exo (iid innovations) need initval; endogenous
// SS values (eps_c=0, R_c_draw=0, etc.) come from the steady solver.
// ---------------------------------------------------------------
initval;
@#for c in COMM
    nu_@{c}      = 0;
    e_@{c}_shock = 0;
@#endfor
end;
steady;

// ---------------------------------------------------------------
// Stochastic shock distributions — ANNUAL MODEL CALIBRATION
//
// MODEL FREQUENCY: 1 period = 1 year.
//
// SUPPLY DISRUPTIONS (e_c_shock) — annual shortages, NOT daily events:
//   In an annual model, e_c_shock < 0 means that fraction of annual
//   imports fails to arrive (e.g., Malacca Strait blockage for several months).
//
//   RECOMMENDED: use SIM_MODE = 'pf' (ToyModelSOEMC_shock_gen.m) which
//   draws Bernoulli crisis events with realistic annual frequency:
//     Onset prob p_crisis = 0.04/year  (major disruption once every 25 years)
//     Magnitude  U(0.20, 0.50) × ED_c_bar  (20-50% of annual imports)
//     Duration   geometric(p_end=0.50)  → avg 2 years
//
//   This calibration ensures reserves MATTER:
//     At 90-day coverage (R_bar = 0.25×ED_bar):
//       Small crisis (20% shortfall) → fully covered → no production loss
//       Large crisis (50% shortfall) → 50% covered → 25% residual shortage
//     E[R_draw] = p_crisis × 0.35 × ED_bar × phi_R ≈ 0.0021/yr
//     E[refill] = delta_R × R_bar + gamma_R × E[gap] ≈ 0.002-0.020/yr ✓
//     → Stock stays near R_bar; insurance value is non-trivial.
//
//   DO NOT use small sigma (e.g., 0.05) in EP mode for annual supply shocks:
//     sigma=0.05 → E[R_draw] ≈ 0.020/yr >> E[refill] ≈ 0.0015/yr → stock depletes
//     → reserves always empty → insurance value = 0 (wrong result)
//     The Gaussian approximation is inappropriate for rare large events.
//
// PRICE INNOVATIONS (nu_c) — annual price volatility for AR(1) state:
//   Annual commodity price volatility: oil ~25-35%, coal ~28-40% p.a.
//   sigma_nu calibrated so unconditional std(eps_c) ≈ 0.25-0.30.
// ---------------------------------------------------------------
shocks;
    var nu_oil;       stderr 0.20;    // oil price innovation (annual): σ_ε = 0.25 unconditional
    var e_oil_shock;  stderr 0.07;    // EP-mode only: Gaussian approx of annual crisis (rarely used)
    var nu_coal;      stderr 0.22;    // coal price innovation (annual): σ_ε = 0.28 unconditional
    var e_coal_shock; stderr 0.07;    // EP-mode only: use PF mode + shock_gen for correct calibration
end;

// ---------------------------------------------------------------
// Extended path: receding-horizon stochastic simulation
//   At each period t, agents solve a perfect-foresight sub-problem
//   of length 'periods' assuming future shocks = 0, then actual
//   innovations are realised and the state advances one step.
//   This is more realistic than one-shot perfect foresight because
//   agents do NOT know the full future shock sequence in advance.
//
//   MC scripts (ToyModelSOEMC_montecarlo.m, _optimal_stock.m)
//   call extended_path directly, varying phi_R and phi_IQ in M_.params.
// ---------------------------------------------------------------
@#if SIMMode == "pf"
    perfect_foresight_setup(periods = 500);
    perfect_foresight_solver;
@#endif

@#if SIMMode == "ep"
    extended_path(periods = 500);
@#endif

